# Generated by Django 4.2.5 on 2023-09-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.CharField(max_length=200)),
                ('duree', models.IntegerField()),
                ('action', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('prix_departement', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix_machine', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantiteingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_level.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_level.action')),
            ],
        ),
        migrations.CreateModel(
            name='Usine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.FloatField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_level.departement')),
                ('machines', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.machine')),
                ('recettes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.recette')),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.quantiteingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_level.departement')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_level.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.quantiteingredient'),
        ),
        migrations.AddField(
            model_name='action',
            name='machines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_level.machine'),
        ),
    ]
