# Generated by Django 4.2.5 on 2023-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usine',
            name='machines',
        ),
        migrations.RemoveField(
            model_name='usine',
            name='stocks',
        ),
        migrations.AddField(
            model_name='usine',
            name='machines',
            field=models.ManyToManyField(to='high_level.machine'),
        ),
        migrations.AddField(
            model_name='usine',
            name='stocks',
            field=models.ManyToManyField(to='high_level.quantiteingredient'),
        ),
    ]
